#!/bin/bash

set -eu

## BUILD amd64

echo "Building amd64 image: START"

docker build --build-arg FROM_IMAGE_NAME="alpine:latest" \
            --build-arg FROM_SRC_IMAGE_NAME="manios/nagios-src-builder:latest" \
            --build-arg GOSU_BIN="gosu-amd64" \
             -f $DOCKERFILE_PATH \
             -t $IMAGE_NAME .

echo "Building amd64 image: SUCCESS"

## BUILD arm32/v6

echo "Enabling qemu-arm-static in Dockerfile"
    sed -i 's/^# *\(COPY qemu-arm-static\)/\1/g' "${DOCKERFILE_PATH}"
    

echo "Building arm32/v6 image: START"

docker build --build-arg FROM_IMAGE_NAME="arm32v6/alpine:latest" \
            --build-arg FROM_SRC_IMAGE_NAME="manios/nagios-src-builder:latest-armv6" \
            --build-arg GOSU_BIN="gosu-armel" \
             -f $DOCKERFILE_PATH \
             -t "$IMAGE_NAME-armv6" .

echo "Building arm32/v6 image: SUCCESS"

## BUILD arm32/v7

echo "Building arm32/v7 image: START"

docker build --build-arg FROM_IMAGE_NAME="arm32v7/alpine:latest" \
            --build-arg FROM_SRC_IMAGE_NAME="manios/nagios-src-builder:latest-armv7" \
            --build-arg GOSU_BIN="gosu-armhf" \
             -f $DOCKERFILE_PATH \
             -t "$IMAGE_NAME-armv7" .

echo "Building arm32/v7 image: SUCCESS"