#!/bin/bash

set -eu

export DOCKER_CLI_EXPERIMENTAL=enabled
MY_MANIFEST_NAME="${IMAGE_NAME}"

# Create a manifest
docker manifest create ${IMAGE_NAME} \
               ${IMAGE_NAME} \
               ${IMAGE_NAME}-armv6 \
               ${IMAGE_NAME}-armv7

# Add variant for armv6
docker manifest annotate ${MY_MANIFEST_NAME} "${IMAGE_NAME}-armv6" --arch arm --os linux --variant v6

# Add variant for armv6
docker manifest annotate ${MY_MANIFEST_NAME} "${IMAGE_NAME}-armv7" --arch arm --os linux --variant v7

echo "Pushing manifest ${MY_MANIFEST_NAME}"

docker manifest push ${MY_MANIFEST_NAME}

echo "Pushing manifest ${MY_MANIFEST_NAME} SUCCESS"