#!/bin/bash

# QEMU version variables
QEMU_EXE=qemu-arm-static
QEMU_VERSION=v4.2.0-4

# download qemu
curl -L https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_VERSION}/${QEMU_EXE}.tar.gz | tar zxvf - -C .

# https://stackoverflow.com/questions/37935415/bash-regex-string-variable-match

# download estep/manifest-tool
curl -L https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64 -o manifest-tool && \
chmod 744 manifest-tool && \
ls -l
