#!/bin/bash

# https://stackoverflow.com/questions/37935415/bash-regex-string-variable-match

NEW_STRING="$1"

REGEX="^([^-]+)-?([^-]+)?$"

echo $NEW_STRING;

[[ $NEW_STRING =~ $REGEX ]]
MY_BRANCH="${BASH_REMATCH[1]}"
MYVARIANT="${BASH_REMATCH[2]}"

if [ -z $MYVARIANT ]; then
    echo "Variant is empty"
fi

echo "Branch: ${MY_BRANCH} . Variant: ${MYVARIANT}"

