#!/bin/sh

set -eu

echo -n "Removing Apache HTTPD PID file before starting it ..."
(rm -f /var/run/apache2/httpd.pid || true)
echo "OK"

. /usr/sbin/envvars

# TODO Check about cache
# . /usr/sbin/htcacheclean

export TZ="${NAGIOS_TIMEZONE}"

exec /usr/sbin/httpd -D NO_DETACH
